export const modalStyle = {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '80%',
    bgcolor: 'white',
    border: '2px solid #000',
    boxShadow: 24,
    borderRadius: '2rem',
    maxHeight: '90%',
    overflow: 'hidden',
    overflowY: 'scroll',
};